name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # runs daily at midnight
  workflow_dispatch: # lets you run it manually

jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: generate snake
        uses: Platane/snk@v3.4.1
        with:
          github_user_name: rani367
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
      
      - name: push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
